# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 09:45
from __future__ import unicode_literals

import Pentagram.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pentagram', '0002_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(null=True, upload_to=Pentagram.models.photos_directory),
        ),
    ]
