# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pentagram', '0004_auto_20160719_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='photo_id',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='user_id',
        ),
        migrations.AddField(
            model_name='photo',
            name='counter_like',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
