# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pentagram', '0006_auto_20160720_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='counter_like',
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=500),
        ),
    ]
