# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pentagram', '0007_auto_20160720_0929'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Comments',
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(default=2, upload_to=''),
            preserve_default=False,
        ),
    ]
